// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6w7K3mtCL7m29hh4Nnb-v9yUVz4j_vUw',
    appId: '1:858736042940:web:9b355da9405be078bec1b9',
    messagingSenderId: '858736042940',
    projectId: 'app1notificacion',
    authDomain: 'app1notificacion.firebaseapp.com',
    storageBucket: 'app1notificacion.appspot.com',
    measurementId: 'G-QBD1K4D298',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEujanHAF9HPDMnR3uDj0WSu9G61MxRIQ',
    appId: '1:858736042940:android:e05e94ab56259d2bbec1b9',
    messagingSenderId: '858736042940',
    projectId: 'app1notificacion',
    storageBucket: 'app1notificacion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8S_CrOKZZ7C8PmRkKS3nYmy2OgtlKk2I',
    appId: '1:858736042940:ios:09b660990e9119a0bec1b9',
    messagingSenderId: '858736042940',
    projectId: 'app1notificacion',
    storageBucket: 'app1notificacion.appspot.com',
    iosClientId: '858736042940-3r2qbnnkpmg85lah37ra7tqchuich9j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificacionesFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8S_CrOKZZ7C8PmRkKS3nYmy2OgtlKk2I',
    appId: '1:858736042940:ios:dce2917f0e3bf3e9bec1b9',
    messagingSenderId: '858736042940',
    projectId: 'app1notificacion',
    storageBucket: 'app1notificacion.appspot.com',
    iosClientId: '858736042940-sikvcm8d5tmog1e6e4sgtn6gqkin18jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificacionesFirebase.RunnerTests',
  );
}
